//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenShotTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeSettings {
            get {
                return ((bool)(this["UpgradeSettings"]));
            }
            set {
                this["UpgradeSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RegisterHotkeys {
            get {
                return ((bool)(this["RegisterHotkeys"]));
            }
            set {
                this["RegisterHotkeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PrintScreen")]
        public string hkCaptureWindowKey {
            get {
                return ((string)(this["hkCaptureWindowKey"]));
            }
            set {
                this["hkCaptureWindowKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkCaptureWindowCtrl {
            get {
                return ((bool)(this["hkCaptureWindowCtrl"]));
            }
            set {
                this["hkCaptureWindowCtrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hkCaptureWindowAlt {
            get {
                return ((bool)(this["hkCaptureWindowAlt"]));
            }
            set {
                this["hkCaptureWindowAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkCaptureWindowShift {
            get {
                return ((bool)(this["hkCaptureWindowShift"]));
            }
            set {
                this["hkCaptureWindowShift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkCaptureWindowWin {
            get {
                return ((bool)(this["hkCaptureWindowWin"]));
            }
            set {
                this["hkCaptureWindowWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PrintScreen")]
        public string hkCaptureRegionKey {
            get {
                return ((string)(this["hkCaptureRegionKey"]));
            }
            set {
                this["hkCaptureRegionKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkCaptureRegionCtrl {
            get {
                return ((bool)(this["hkCaptureRegionCtrl"]));
            }
            set {
                this["hkCaptureRegionCtrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkCaptureRegionAlt {
            get {
                return ((bool)(this["hkCaptureRegionAlt"]));
            }
            set {
                this["hkCaptureRegionAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkCaptureRegionShift {
            get {
                return ((bool)(this["hkCaptureRegionShift"]));
            }
            set {
                this["hkCaptureRegionShift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkCaptureRegionWin {
            get {
                return ((bool)(this["hkCaptureRegionWin"]));
            }
            set {
                this["hkCaptureRegionWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hkBrowseFolderKey {
            get {
                return ((string)(this["hkBrowseFolderKey"]));
            }
            set {
                this["hkBrowseFolderKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkBrowseFolderCtrl {
            get {
                return ((bool)(this["hkBrowseFolderCtrl"]));
            }
            set {
                this["hkBrowseFolderCtrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkBrowseFolderAlt {
            get {
                return ((bool)(this["hkBrowseFolderAlt"]));
            }
            set {
                this["hkBrowseFolderAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkBrowseFolderShift {
            get {
                return ((bool)(this["hkBrowseFolderShift"]));
            }
            set {
                this["hkBrowseFolderShift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkBrowseFolderWin {
            get {
                return ((bool)(this["hkBrowseFolderWin"]));
            }
            set {
                this["hkBrowseFolderWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PrintScreen")]
        public string hkCaptureCurrentScreenKey {
            get {
                return ((string)(this["hkCaptureCurrentScreenKey"]));
            }
            set {
                this["hkCaptureCurrentScreenKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hkCaptureCurrentScreenCtrl {
            get {
                return ((bool)(this["hkCaptureCurrentScreenCtrl"]));
            }
            set {
                this["hkCaptureCurrentScreenCtrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkCaptureCurrentScreenAlt {
            get {
                return ((bool)(this["hkCaptureCurrentScreenAlt"]));
            }
            set {
                this["hkCaptureCurrentScreenAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkCaptureCurrentScreenShift {
            get {
                return ((bool)(this["hkCaptureCurrentScreenShift"]));
            }
            set {
                this["hkCaptureCurrentScreenShift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkCaptureCurrentScreenWin {
            get {
                return ((bool)(this["hkCaptureCurrentScreenWin"]));
            }
            set {
                this["hkCaptureCurrentScreenWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hkCaptureAllScreensKey {
            get {
                return ((string)(this["hkCaptureAllScreensKey"]));
            }
            set {
                this["hkCaptureAllScreensKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkCaptureAllScreensCtrl {
            get {
                return ((bool)(this["hkCaptureAllScreensCtrl"]));
            }
            set {
                this["hkCaptureAllScreensCtrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkCaptureAllScreensShift {
            get {
                return ((bool)(this["hkCaptureAllScreensShift"]));
            }
            set {
                this["hkCaptureAllScreensShift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkCaptureAllScreensAlt {
            get {
                return ((bool)(this["hkCaptureAllScreensAlt"]));
            }
            set {
                this["hkCaptureAllScreensAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hkCaptureAllScreensWin {
            get {
                return ((bool)(this["hkCaptureAllScreensWin"]));
            }
            set {
                this["hkCaptureAllScreensWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$w $d $t $c")]
        public string Filename {
            get {
                return ((string)(this["Filename"]));
            }
            set {
                this["Filename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\$w")]
        public string Foldername {
            get {
                return ((string)(this["Foldername"]));
            }
            set {
                this["Foldername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".png")]
        public string FileExtension {
            get {
                return ((string)(this["FileExtension"]));
            }
            set {
                this["FileExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TrimChecked {
            get {
                return ((bool)(this["TrimChecked"]));
            }
            set {
                this["TrimChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int TrimTop {
            get {
                return ((int)(this["TrimTop"]));
            }
            set {
                this["TrimTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int TrimBottom {
            get {
                return ((int)(this["TrimBottom"]));
            }
            set {
                this["TrimBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int TrimLeft {
            get {
                return ((int)(this["TrimLeft"]));
            }
            set {
                this["TrimLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int TrimRight {
            get {
                return ((int)(this["TrimRight"]));
            }
            set {
                this["TrimRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Capture")]
        public string AlternateTitle {
            get {
                return ((string)(this["AlternateTitle"]));
            }
            set {
                this["AlternateTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int TitleMaxLength {
            get {
                return ((int)(this["TitleMaxLength"]));
            }
            set {
                this["TitleMaxLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SplitTitleString {
            get {
                return ((string)(this["SplitTitleString"]));
            }
            set {
                this["SplitTitleString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SplitTitleIndex {
            get {
                return ((int)(this["SplitTitleIndex"]));
            }
            set {
                this["SplitTitleIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("95")]
        public long JpegQuality {
            get {
                return ((long)(this["JpegQuality"]));
            }
            set {
                this["JpegQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartHidden {
            get {
                return ((bool)(this["StartHidden"]));
            }
            set {
                this["StartHidden"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CropThumbnails {
            get {
                return ((bool)(this["CropThumbnails"]));
            }
            set {
                this["CropThumbnails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int ThumbnailWidth {
            get {
                return ((int)(this["ThumbnailWidth"]));
            }
            set {
                this["ThumbnailWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ThumbnailHeight {
            get {
                return ((int)(this["ThumbnailHeight"]));
            }
            set {
                this["ThumbnailHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowTrayTooltipWarning {
            get {
                return ((bool)(this["AllowTrayTooltipWarning"]));
            }
            set {
                this["AllowTrayTooltipWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowTrayTooltipInfoFolder {
            get {
                return ((bool)(this["AllowTrayTooltipInfoFolder"]));
            }
            set {
                this["AllowTrayTooltipInfoFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowTrayTooltipInfoCapture {
            get {
                return ((bool)(this["AllowTrayTooltipInfoCapture"]));
            }
            set {
                this["AllowTrayTooltipInfoCapture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegionCompletesOnMouseRelease {
            get {
                return ((bool)(this["RegionCompletesOnMouseRelease"]));
            }
            set {
                this["RegionCompletesOnMouseRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RegionToFile {
            get {
                return ((bool)(this["RegionToFile"]));
            }
            set {
                this["RegionToFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegionToClipboard {
            get {
                return ((bool)(this["RegionToClipboard"]));
            }
            set {
                this["RegionToClipboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegionToEditor {
            get {
                return ((bool)(this["RegionToEditor"]));
            }
            set {
                this["RegionToEditor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WindowToFile {
            get {
                return ((bool)(this["WindowToFile"]));
            }
            set {
                this["WindowToFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WindowToClipboard {
            get {
                return ((bool)(this["WindowToClipboard"]));
            }
            set {
                this["WindowToClipboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WindowToEditor {
            get {
                return ((bool)(this["WindowToEditor"]));
            }
            set {
                this["WindowToEditor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ScreenToFile {
            get {
                return ((bool)(this["ScreenToFile"]));
            }
            set {
                this["ScreenToFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScreenToClipboard {
            get {
                return ((bool)(this["ScreenToClipboard"]));
            }
            set {
                this["ScreenToClipboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScreenToEditor {
            get {
                return ((bool)(this["ScreenToEditor"]));
            }
            set {
                this["ScreenToEditor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllScreensToFile {
            get {
                return ((bool)(this["AllScreensToFile"]));
            }
            set {
                this["AllScreensToFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllScreensToClipboard {
            get {
                return ((bool)(this["AllScreensToClipboard"]));
            }
            set {
                this["AllScreensToClipboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllScreensToEditor {
            get {
                return ((bool)(this["AllScreensToEditor"]));
            }
            set {
                this["AllScreensToEditor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int MaxFramerate {
            get {
                return ((int)(this["MaxFramerate"]));
            }
            set {
                this["MaxFramerate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MaskRegion {
            get {
                return ((bool)(this["MaskRegion"]));
            }
            set {
                this["MaskRegion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Counter {
            get {
                return ((int)(this["Counter"]));
            }
            set {
                this["Counter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int BlurMosaicSize {
            get {
                return ((int)(this["BlurMosaicSize"]));
            }
            set {
                this["BlurMosaicSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int BlurSampleArea {
            get {
                return ((int)(this["BlurSampleArea"]));
            }
            set {
                this["BlurSampleArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MinimizeOnClose {
            get {
                return ((bool)(this["MinimizeOnClose"]));
            }
            set {
                this["MinimizeOnClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SelectAfterPlacingSymbol {
            get {
                return ((bool)(this["SelectAfterPlacingSymbol"]));
            }
            set {
                this["SelectAfterPlacingSymbol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int GsNumberedDefaultSize {
            get {
                return ((int)(this["GsNumberedDefaultSize"]));
            }
            set {
                this["GsNumberedDefaultSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color GsNumberedColor {
            get {
                return ((global::System.Drawing.Color)(this["GsNumberedColor"]));
            }
            set {
                this["GsNumberedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color NewSymbolLineColor {
            get {
                return ((global::System.Drawing.Color)(this["NewSymbolLineColor"]));
            }
            set {
                this["NewSymbolLineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color NewSymbolFillColor {
            get {
                return ((global::System.Drawing.Color)(this["NewSymbolFillColor"]));
            }
            set {
                this["NewSymbolFillColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int NewSymbolLineWeight {
            get {
                return ((int)(this["NewSymbolLineWeight"]));
            }
            set {
                this["NewSymbolLineWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegionCaptureUseAllScreens {
            get {
                return ((bool)(this["RegionCaptureUseAllScreens"]));
            }
            set {
                this["RegionCaptureUseAllScreens"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SelectAfterFreehand {
            get {
                return ((bool)(this["SelectAfterFreehand"]));
            }
            set {
                this["SelectAfterFreehand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\stickers")]
        public string StickerFolder {
            get {
                return ((string)(this["StickerFolder"]));
            }
            set {
                this["StickerFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PreventDpiRescale {
            get {
                return ((bool)(this["PreventDpiRescale"]));
            }
            set {
                this["PreventDpiRescale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%localappdata%\\ScreenshotTool\\TagData")]
        public string TagDataFolder {
            get {
                return ((string)(this["TagDataFolder"]));
            }
            set {
                this["TagDataFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TagMultiSelect {
            get {
                return ((bool)(this["TagMultiSelect"]));
            }
            set {
                this["TagMultiSelect"] = value;
            }
        }
    }
}
